# run: conda env create --file environment.yml
name: audio2
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - pytorch::torchaudio=0.12.1
  - cudatoolkit=11.3
  - pip=22.2.2
  - pip:
    - transformers==4.22.2
    - datasets==2.5.2
    - git+https://github.com/openai/whisper.git
    - pydub==0.25.1
    - rapidfuzz==2.11.1
    - nltk==3.7
    - lxml==4.9.1
    - aeneas==1.7.3.0
    - num2words==0.5.12
    - tabulate==0.9.0
    - pyannote.audio==2.1.1
    - tqdm==4.64.1
    - pyarrow==9.0.0