# run: conda env create --file environment.yml
name: audio
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pytorch::pytorch=1.13.1
  - pytorch::torchaudio=0.13.1
  - pytorch-cuda=11.6
  - pip=23.0.1
  - pip:
    - transformers==4.26.1
    - datasets==2.10.0
    - pydub==0.25.1
    - rapidfuzz==2.11.1
    - nltk==3.7
    - lxml==4.9.1
    - aeneas==1.7.3.0
    - num2words==0.5.12
    - tabulate==0.9.0
    - pyannote.audio==2.1.1
    - mutagen==1.46.0
    - tqdm==4.64.1
    - pyarrow==11.0.0